### ISSUE TITLE
DQN throws unexpected keyword argument 'dim'

### ISSUE THREAD

**Issue by Phantomb** [tesslerc/malmo_rl#4]
On the latest version, I get the following error:
```
> python main.py dqn single_room --double_dqn --normalize_reward --malmo_ports 10001
2018-01-16 15:57:36 INFO: To view results, run 'python -m visdom.server'
2018-01-16 15:57:36 INFO: then head over to http://localhost:8097
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    True)
  File "C:\Github_Repos\tessler_Malmo\utilities\helpers.py", line 52, in play_full_episode
    action = policy.get_action(states, is_train)
  File "C:\Github_Repos\tessler_Malmo\policies\dqn.py", line 125, in get_action
    self.previous_states = np.expand_dims(self.previous_states, dim=0)
TypeError: expand_dims() got an unexpected keyword argument 'dim'
```
The relevant commit is 9866be57fd22d74279ad8ccc2e3549eeb07ca3cc.

Did you mean to use 'axis' in place of dim?

**Comment by tesslerc** [comment]
Thanks! I have been using retain_rgb for a while, which is probably why I missed this.
d2a30f56c856c02203f2d497b495425ac3d069e4

Tell me if you still encounter any issues 👍

**Comment by tesslerc** [comment]
Assuming fixed.

**Comment by Phantomb** [comment]
Yes it seems fixed. I initially missed your reply to this, apologies.
